spring:
  application:
    name: taskflow

  jwt:
    secret: ${SECRET:my-super-secret-key-for-taskflow-management-jwt-2026}

  datasource:
    url: jdbc:postgresql://localhost:5432/taskflow
    username: taskflow
    password: taskflow

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

  logging:
    level:
      org.springframework.security: DEBUG