spring:
  application:
    name: taskflow

  datasource:
    url: jdbc:postgresql://localhost:5432/taskflow
    username: taskflow
    password: taskflow

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
